raptor-launcer:
  version: 2.0
  home: "/Users/matkat"
  timezone: "Europe/Sofia"
  lang: "en_US.UTF-8"
  database_url: "postgres://admin:1234@localhost:5432/vehicles"

docker:
  enabled: true
  compose_workdir: "${DOCKER_COMPOSE_WORKDIR}"

  commands:
    start_docker_linux: "sudo systemctl start docker"
    stop_docker_linux: "sudo systemctl stop docker"

    # macOS
    start_docker_mac: "open --background -a Docker"
    stop_docker_mac: 'killall "Docker Desktop" "com.docker.backend" 2>/dev/null || true'

    is_alive: "docker info > /dev/null 2>&1 && echo ok || echo error"
    list_containers: "docker ps --format '{{.Names}}'"
    is_container_running: "docker inspect -f '{{.State.Running}}' {{container}}"

    start_compose: "cd {{workdir}} && docker compose up -d"
    stop_compose: "cd {{workdir}} && docker compose down"
    restart_compose: "cd {{workdir}} && docker compose restart"

    start_container: "cd {{workdir}} && docker compose up -d --no-recreate {{container}}"
    stop_container: "cd {{workdir}} && docker compose stop {{container}}"
    restart_container: "cd {{workdir}} && docker compose restart {{container}}"

  containers:
    - "kafka-server"
    - "postgres-server"
    - "web-admin"

kafka:
  container: "kafka-server"
  bootstrap_server: "localhost:9092"

  configs:
    retention:
      ms: 86400000 # 24 часа
      bytes: 104857600 # 100 MB

  topics:
    mobile_de: "raptor.mobile_de"
    metadata: "raptor.metadata"

  commands:
    list_topics: "docker exec {{container}} /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server {{bootstrap}}"

    create_topic:
      "docker exec {{container}} /opt/kafka/bin/kafka-topics.sh --create \
      --topic {{topic}} --partitions 1 --replication-factor 1 \
      --bootstrap-server {{bootstrap}} --if-not-exists"

    alter_topic:
      "docker exec {{container}} /opt/kafka/bin/kafka-configs.sh --alter \
      --bootstrap-server {{bootstrap}} --entity-type topics \
      --entity-name {{topic}} \
      --add-config retention.ms={{retention_ms}},retention.bytes={{retention_bytes}}"

    describe_topic:
      "docker exec {{container}} /opt/kafka/bin/kafka-configs.sh --describe \
      --bootstrap-server {{bootstrap}} --entity-type topics --entity-name {{topic}}"

chrome:
  enabled: true
  port: 9223
  version_url: "http://127.0.0.1:{{port}}/json/version"
  start_cmd: "devops/bin/start-chrome.sh"
  stop_cmd: "pkill -f remote-debugging-port={{port}} || true"
  grep_cmd: "pgrep -fa 'chrome.*remote-debugging-port={{port}}' || echo 'not found'"

raptor-services:
  mobile_de:
    enabled: true
    start_script: "devops/bin/start-mobile_de.sh"
    stop_script: "devops/bin/stop-mobile_de.sh"
    grep_cmd: "pgrep -fa 'mobile_de' || echo 'not found'"

  crawler-ro:
    enabled: true
    start_script: "devops/bin/start-crawler.sh autouncle.ro"
    stop_script: "devops/bin/stop-crawler.sh"
    grep_cmd: "pgrep -fa 'crawler --source' || echo 'not found'"

  crawler-fr:
    enabled: true
    start_script: "devops/bin/start-crawler.sh autouncle.fr"
    stop_script: "devops/bin/stop-crawler.sh"
    grep_cmd: "pgrep -fa 'crawler --source' || echo 'not found'"

  crawler-it:
    enabled: true
    start_script: "devops/bin/start-crawler.sh autouncle.it"
    stop_script: "devops/bin/stop-crawler.sh"
    grep_cmd: "pgrep -fa 'crawler --source' || echo 'not found'"

  crawler-nl:
    enabled: true
    start_script: "devops/bin/start-crawler.sh autouncle.nl"
    stop_script: "devops/bin/stop-crawler.sh"
    grep_cmd: "pgrep -fa 'crawler --source' || echo 'not found'"

  crawler-de:
    enabled: true
    start_script: "devops/bin/start-crawler.sh autouncle.de"
    stop_script: "devops/bin/stop-crawler.sh"
    grep_cmd: "pgrep -fa 'crawler --source' || echo 'not found'"

  crawler-pl:
    enabled: true
    start_script: "devops/bin/start-crawler.sh autouncle.pl"
    stop_script: "devops/bin/stop-crawler.sh"
    grep_cmd: "pgrep -fa 'crawler --source' || echo 'not found'"

  crawler-ch:
    enabled: true
    start_script: "devops/bin/start-crawler.sh autouncle.ch"
    stop_script: "devops/bin/stop-crawler.sh"
    grep_cmd: "pgrep -fa 'crawler --source' || echo 'not found'"

  crawler-bg:
    enabled: true
    start_script: "devops/bin/start-crawler.sh mobile.bg"
    stop_script: "devops/bin/stop-crawler.sh"
    grep_cmd: "pgrep -fa 'crawler --source' || echo 'not found'"

  raptor:
    enabled: true
    start_script: "devops/bin/start-raptor.sh mobile.de"
    stop_script: "devops/bin/stop-raptor.sh"
    grep_cmd: "pgrep -fa 'make start' || echo 'not found'"
